### PR TITLE
Deutsch Edition (for added comedic effect)

### PR DESCRIPTION
**Pull request by stimpak-addict**
I added some new terms to the list and modified the language to be more genetically pure. I also added some other translations towards the bottom in comments that could be used. I hope my translations aren't too crude.

### CODE REVIEW

**Comment by Alcesmire** [comment]
As much as I admire the work you've done I think it would be preferable to keep the editions separate. If you want to I could put a link in the readme to redirect peers who want some more linguistic purity to your fork, though.

**Comment by stimpak-addict** [comment]
I can understand that. I’m fairly new to using Github, so I didn’t know fully what I was doing with the pull request. I was trying to make a different branch (or fork) for the purpose of making them separate options for people much like you said. I wouldn’t want to overwrite the work that you have done.

Also, I notice you’re from Sweden. From what I hear, you guys aren’t having such a good time right now. Wishing you all the best over there! I really admire your country.

••Hunter•

**Comment by Alcesmire** [comment]
I added a link to your fork to the readme in 31b186af78004ff64eb767bb49b285ab17741081.

As for the state of Sweden, it's not as bad as people make it out to be. It's not good, but it's not dramatically bad like the internet like to claim (although I must be wrong since /pol/ is always right).

**Comment by stimpak-addict** [comment]
Awesome!

You have obviously just been going too heavy on the blue pills. ;^)

••Hunter•

**Pull request closed without merging**
